name: Auto-testing workflow with Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app
  GOOGLE_SERVICE_INFO_PLIST_PATH: fusion/fusion/GoogleService-Info.plist

jobs:
  testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s ${{ env.DEVELOPER_DIR }}

      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install

      - uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: install Pods
        run: bundle exec pod install

      - run: |
          cd fusion/fusion
          touch GoogleService-Info.plist

      - name: Decode GoogleService-Info.plist
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_CONTENT }} | base64 -o ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }} -D

      - name: fastlane
        run: bundle exec fastlane test
