name: Auto-testing workflow with Fastlane

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: bundle install
        run: bundle install
      - name: install Pods
        run: bundle exec pod install
      - env:
          APPLE_ID: ${{ secrets.APPLE_ID}}
      - name: fastlane
        run: bundle exec fastlane test

